---
- name: Force handlers to restart sshd. From now on it responds to inventory port.
  meta: flush_handlers

- name: Restore ansible_port back to inventory port.
  set_fact:
    ansible_port: "{{ ssh_server_ports[0] }}"

- debug:
    msg: "Restoring port from 22 back to {{ ssh_server_ports[0] }}."