---
- name: Fallback to port 22 if server still answering on that port.
  include_tasks: before.yml
  when: ansible_port is defined and ansible_port != 22

- name: Run setup to gather facts if not yet done.
  setup:
  when: ansible_facts.distribution is undefined

- name: Include actual ssh-hardening role (which doesn't fallback to default port).
  include_role:
    name: dev-sec.ssh-hardening

- name: Revert port from 22 back to inventory port.
  include_tasks: after.yml
  when: ssh_hardening_fallback is defined